### ISSUE TITLE
x2gbfs fails for stadtmobil_stuttgart

### ISSUE THREAD

**Issue by ThorstenFroehlinghaus** [mobidata-bw/x2gbfs#115]
https://[test-ipl.mobidata-bw.de/sharing/gbfs/stadtmobil_stuttgart/gbfs](https://test-ipl.mobidata-bw.de/sharing/gbfs/stadtmobil_stuttgart/gbfs) is not accessible. The x2gbfs log shows:

![image](https://github.com/mobidata-bw/x2gbfs/assets/120580045/be2dd0eb-4c05-410e-9050-494d07ec9bd3)

There seems to be an unexpected Booking Class. However, the exception does not report the unexpected value.

**Comment by hbruch** [comment]
The missing pricing_plan_id `large` is reported in the last line, no?

**Comment by ThorstenFroehlinghaus** [comment]
Ok, you right. I just noticed the template text.
This seems to be a data issue because stuttgart uses 'large' as a new Bookee Class without changing its pricing model.
I suggest not to break the feed, but to raise a Warning and to skip such Bookees with unextected Class.

**Comment by hbruch** [comment]
This is already added in branch [cantamen_pricing](https://github.com/mobidata-bw/x2gbfs/commit/2370cd4cdcd4e99d703fa91131023f84178e4d85)

**Comment by ThorstenFroehlinghaus** [comment]
Ok, now x2gbfs sais:
WARNING:x2gbfs.cantamen:Could not extract vehicle/vehicle_type for bookee 27704 due to exception:
Traceback (most recent call last):
  File "/home/ipl/ipl12_x2gbfs/x2gbfs/providers/cantamen.py", line 341, in load_vehicles
    vehicle_type = self._extract_vehicle_type(bookee)
  File "/home/ipl/ipl12_x2gbfs/x2gbfs/providers/cantamen.py", line 261, in _extract_vehicle_type
    default_pricing_plan_id, pricing_plan_ids = self._extract_pricing_plan_ids(bookee, attributes)
  File "/home/ipl/ipl12_x2gbfs/x2gbfs/providers/cantamen.py", line 228, in _extract_pricing_plan_ids
    raise ValueError(f'Unexpected bookee class {default_pricing_plan_id} is no pricing_plan_id')

Do you want to merge this branch? Then I can update test-ipl.

**Comment by hbruch** [comment]
Could you still add the large_* pricing_plans and create a PR?

**Comment by hbruch** [comment]
This is also fixed by #117
